
name: Azure
on:
  workflow_dispatch:
jobs:
  tests:
    name: "Turn on vm"
    runs-on: ubuntu-latest
    steps:    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Run image in container
      run: |
        docker run --rm apon77/az /bin/bash -c "az vm start -g K_group -n K" && echo success || echo Failed
